### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ajafff** [fimbullinter/wotan#764]
This issue lists the planned work items for the next few releases. This list exists so you know where this project is headed and how I will probably spend my time. Tasks are not ordered by priority. I might not strictly follow the roadmap if something else needs to be addressed earlier or is a low-hanging fruit.

If you'd like to see another feature on this list, let's discuss this in the comments below.

### Increasing productivity and ease of use

Things that bother me and would also make this project more useful for a broader audience.

- [ ] enable fixes in LanguageService plugin
- [ ] #316 introduce code actions
- [ ] #255 Angular integration

### Accessibility for new users / documentation overhaul

Restructuring and rewriting the existing documentation to make it actually useful. Top priority are new users. Rule authors are also a high priority target. Feedback is very welcome.

- [ ] #746 Make conguration easier for new users
- [ ] #17 add missing configuration for all features

### Tap into ESLint ecosystem

ESLint has a vast amount of (mostly) useful rules. Combined with Wotan's understanding of TypeScript (default excluded files, caching, potentially watch mode, ...) this might become more useful than typescript-eslint.

- [ ] #517 allow using ESLint rules
- [ ] Enable use of existing ESLint configuration
- [ ] probably goes along with configuration overhaul #635 

### Features and Stability

- [ ] #760 Cache should track rules accessing other source files
- [ ] #479 Watch mode
- [ ] Allow rules to access the file system through RuleContext
- [ ] Add scope analysis to RuleContext
- [ ] stretch goal: complete control flow graph
